spring:
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true #opcional
    application:
        name: mange.racing.api
    datasource:
        url: jdbc:mysql://localhost:3306/mangeracing?createDatabaseIfNotExist=true
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

server:
    port: 3000